// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: envoy/service/tap/v2alpha/tds.proto

package envoy_service_tap_v2alpha

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/gogo/protobuf/types"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = types.DynamicAny{}
)

// Validate checks the field values on TapConfiguration with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *TapConfiguration) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Name

	{
		tmp := m.GetConfig()

		if v, ok := interface{}(tmp).(interface{ Validate() error }); ok {

			if err := v.Validate(); err != nil {
				return TapConfigurationValidationError{
					field:  "Config",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}
	}

	return nil
}

// TapConfigurationValidationError is the validation error returned by
// TapConfiguration.Validate if the designated constraints aren't met.
type TapConfigurationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TapConfigurationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TapConfigurationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TapConfigurationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TapConfigurationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TapConfigurationValidationError) ErrorName() string { return "TapConfigurationValidationError" }

// Error satisfies the builtin error interface
func (e TapConfigurationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTapConfiguration.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TapConfigurationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TapConfigurationValidationError{}
